#!/usr/bin/env bash
# A Bash script that displays the time for 12 hours and 59 minutes:
# display hours from 0 to 12
# display minutes from 1 to 59

minute=1
hour=0

while [[ $hour -le 12 ]]; do
    while [[ $minute -le 59 ]]; do
        printf "%02d:%02d\n" $hour $minute
        minute=$((minute + 1))
    done
    hour=$((hour + 1))
    minute=0
done | head -n 70
